spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/messages?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: passw
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        github:
          clientId: f16ad5da1640507c86b4
          clientSecret: 5affafecd317dcdb2520c93fdf4847f5e02f46ad
server:
  port: 8081

ums:
  host: http://127.0.0.1
  port: 8080